// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpqukapttefihehpyhwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcXVrYXB0dGVmaWhlaHB5aHdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MzQyNjgsImV4cCI6MjA2ODMxMDI2OH0.IOhB7xiwXD8ZPT98jpXNb8Hj7hibYuHwa813AOIiRJA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});